# Workflow Name
name: build, push, deploy and register geocore services

# Workflow Triggers
on:
  # Triggered on push of a new tag
  push:
    tags:
      - 'v*.*.*'

# Workflow Environment Variables
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  REGION: asia-south1

# Workflow Jobs
jobs:
  push-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        services: [geocore-spatio, geocore-chrono, geocore-raster]

    steps:
      # Checkout Git Repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Set Tag Environment Variable
      - name: Set Tag Environment Value
        run: echo "TAG_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      # Configure gcloud SDK
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}

      # Authorize Docker for gcloud Artifact Registry
      - name: Authorize Docker Push
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      # Build Docker Image
      - name: Build Image
        run: docker build ./${{ matrix.services }} -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/geocore/${{ matrix.services }}:${{ env.TAG_VERSION }}

      # Push Docker Image
      - name: Push Image to Artifact Registry
        run: docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/geocore/${{ matrix.services }}:${{ env.TAG_VERSION }}

      # Deploy Service
      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@main
        with: 
          service: ${{ matrix.services }}
          region: ${{ env.REGION }}
          env_vars: GCP_PROJECT=${{ env.PROJECT_ID }}, GCP_REGION=${{ env.REGION }}, MAPS_APIKEY=${{ secrets.MAPS_APIKEY }}
          flags: --service-account ${{ matrix.services }}@${{ secrets.GCP_PROJECT }}.iam.gserviceaccount.com --timeout 60 --concurrency 5
          image: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/geocore/${{ matrix.services }}:${{ env.TAG_VERSION }}

      # Register Service
      - name: Register with Service Directory
        run: | 
          gcloud service-directory services update ${{ matrix.services }} \
            --namespace geocore \
            --location ${{ env.REGION }} \
            --annotations url="${{ steps.deploy.outputs.url }}"
